[package]
name = "sample"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
chrono = { version = "0.4.42", features = ["serde"] }
domner_tech_sql_client ={ path = "../domner_tech_sql_client", features = ["mssql", "pgsql"]}
tokio = {version = "1.47.1", features = ["full"]}
